### PR TITLE
Added initial structure for the documentation

### PR DESCRIPTION
**Pull request by soffokl**
You can take a look on overall view of the documentation here:
https://docs.mysterium.network

### CODE REVIEW

**Review by tadovas — APPROVED** [review]
¯\\_(ツ)_/¯

**Review by vkuznecovas — APPROVED** [review]

**Comment by zolia** [comment]
How will we maintain this? That is how we should keep it in sync with github Wiki etc. Or the idea is to scrap wiki at all? Also main README.md i imagine will be left where it is?

**Review by zolia — CHANGES_REQUESTED** [review]
Need to discuss, how we will be maintaining it. Should our AC always include editing this project in parallel?

**Comment by soffokl** [comment]
@zolia I think that it is better to have a single place for documentation to avoid inconsistency. 
If we need to keep wiki we can sync this documentation to the wiki, I've created an issue for that https://github.com/mysteriumnetwork/docs/issues/5

**Comment by zolia** [comment]
But we should have at least minimal README.md on each project locally. Since without it it does not look good. Question is what info should be left out.

**Review by interro — APPROVED** [review]
Looks great

**Review by zolia — APPROVED** [review]

**Pull request merged**
