### PR TITLE
Bintray link replaced by Sonatype

### PR DESCRIPTION
**Pull request by soffokl**

### CODE REVIEW

**Review by tadovas — APPROVED** [review]

**Comment by tadovas** [comment]
But this should be postponed until we actually deploy to maven right?

**Comment by soffokl** [comment]
@tadovas 0.5.1 already deployed. The latest version will be deployed after https://github.com/mysteriumnetwork/node/pull/666 merge.

**Comment by tadovas** [comment]
Awesome 👍

**Review by vkuznecovas — APPROVED** [review]

**Comment by donce** [comment]
@soffokl please let me know once the latest version is in Sonartype - we'll migrate mobile to use it :)

**Pull request merged**
